services:
  traefik:
    image: traefik-aws
    pull_policy: build
    build:
      context: ./traefik
    restart: unless-stopped
    command:
#      - --accesslog=true
#      - --accesslog.format=json
#      - --accesslog.fields.defaultmode=keep
#      - --accesslog.fields.headers.defaultmode=keep
#      - --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --log.level=${LOG_LEVEL:-info}
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=route53
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.address=:${TRAEFIK_WEB_HTTP_PORT}
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:${TRAEFIK_WEB_PORT}
    ports:
      - ${TRAEFIK_WEB_PORT}:${TRAEFIK_WEB_PORT}/tcp
      - ${TRAEFIK_WEB_HTTP_PORT}:${TRAEFIK_WEB_HTTP_PORT}/tcp
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/letsencrypt
      - ~/.aws:/root/.aws:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  bitcoind:
    depends_on:
    - traefik
volumes:
  certs:
