name: Build and scan container for vulnerabilities with Trivy

on:
  push:
    paths:
    - 'Dockerfile'
  pull_request:
    paths:
    - 'Dockerfile'
  schedule:
    - cron: '22 14 * * 0'
  workflow_dispatch:

jobs:
  build:
    name: Build and scan images
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: Build image from Dockerfile
        uses: docker/build-push-action@v3.2.0
        with:
          push: false
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bitcoind:latest
      - 
        name: Run Trivy vulnerability scanner against "latest" image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/bitcoind:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - 
        name: Upload "latest" Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
