name: "Update image when Dockerfile is changed"

on:
  push:
    branches:
    - main
    paths:
    - 'Dockerfile'
  workflow_dispatch:

jobs:
  rebuild-container:
    name: "Rebuild Container with the latest base image"
    runs-on: ubuntu-latest
    steps:
      - 
        name: Prepare outputs
        id: prep
        run: |
          echo "::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        with:
          platforms: linux/arm64
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2.1.0 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Get Sparrow version
        id: get_tag
        run: echo "::set-output name=tag::$(awk -F '=' '/VERSION=/ {print $2}' Dockerfile)"
      - 
        name: Build x86_64 image
        id: docker_build_amd64
        uses: docker/build-push-action@v3.2.0
        with:
          push: false
          load: true
          platforms: linux/amd64
          tags: bitcoind:amd64
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/bitcoind:latest
          cache-to: type=inline
      - 
        name: Test-run x86_64 image
        run: |
          docker run --rm bitcoind:ubuntu-test &
          PID=$!
          sleep 60
          kill -SIGINT $PID # this will return a non-zero exit code if the container dies early on
      - 
        name: Build and push to Docker Hub and GitHub Packages Docker Registry
        uses: docker/build-push-action@v3.2.0
        id: docker_build_push
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/bitcoind:latest
            ghcr.io/${{ github.repository_owner }}/bitcoind:${{ steps.get_tag.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/bitcoind:latest
            ${{ secrets.DOCKER_USERNAME }}/bitcoind:${{ steps.get_tag.outputs.tag }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/bitcoind:latest
          cache-to: type=inline
